"""PTY subsystem: tmux session management, POSIX and Windows terminal sessions."""

from __future__ import annotations

from core.web.pty.common import (
    _PTY_QUEUE_MAX_SIZE,
    SHELL_ENGINE,
    PtySession,
    SpawnError,
    _enqueue_pty_output,
    _resize_fd,
)
from core.web.pty.session_posix import (
    _PosixSession,
    _spawn_posix,
    _tmux_resize_window,
)
from core.web.pty.session_windows import (
    _spawn_windows,
    _WindowsSession,
    winpty,
)
from core.web.pty.tmux import (
    _ACTIVE_SESSIONS,
    _DEFAULT_TMUX_SOCKET,
    _MAX_COLS,
    _MAX_PROMPT_CHARS,
    _MAX_ROWS,
    _MIN_COLS,
    _MIN_ROWS,
    _PENDING_PROMPTS,
    _PROMPT_TTL_SECONDS,
    _TAB_KEY_RE,
    _TMUX_SOCKET_ENV,
    _entry_for_tmux_name,
    _purge_expired_prompts,
    _run_tmux,
    _stage_prompt,
    _take_prompt,
    _tmux_binary,
    _tmux_engine_gone,
    _tmux_ensure_session,
    _tmux_has_session,
    _tmux_kill_session,
    _tmux_pane_pid,
    _tmux_session_name,
    _tmux_socket,
    kill_tmux_server,
    list_active_sessions,
    prune_detached_sessions,
    start_tmux_watchdog,
    stop_active_session,
)

__all__ = [
    "PtySession",
    "SpawnError",
    "_enqueue_pty_output",
    "_resize_fd",
    "_PTY_QUEUE_MAX_SIZE",
    "SHELL_ENGINE",
    "_PosixSession",
    "_spawn_posix",
    "_tmux_resize_window",
    "_WindowsSession",
    "_spawn_windows",
    "winpty",
    "_ACTIVE_SESSIONS",
    "_DEFAULT_TMUX_SOCKET",
    "_MAX_COLS",
    "_MAX_PROMPT_CHARS",
    "_MAX_ROWS",
    "_MIN_COLS",
    "_MIN_ROWS",
    "_PENDING_PROMPTS",
    "_PROMPT_TTL_SECONDS",
    "_TAB_KEY_RE",
    "_TMUX_SOCKET_ENV",
    "_entry_for_tmux_name",
    "_purge_expired_prompts",
    "_run_tmux",
    "_stage_prompt",
    "_take_prompt",
    "_tmux_binary",
    "_tmux_engine_gone",
    "_tmux_ensure_session",
    "_tmux_has_session",
    "_tmux_kill_session",
    "_tmux_pane_pid",
    "_tmux_session_name",
    "_tmux_socket",
    "kill_tmux_server",
    "list_active_sessions",
    "prune_detached_sessions",
    "start_tmux_watchdog",
    "stop_active_session",
]
