#!/usr/bin/env python3
"""自动启动 OpenCode 并执行任务 (统一架构版)"""
# ruff: noqa: E402

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List

# 确保能找到 core 模块
sys.path.append(str(Path(__file__).resolve().parent.parent))

from core.cli_utils import require_engine_cli
from core.engine_base import BaseEngine
from core.task_lib import (
    TASK_FILE_SUFFIX,
    handle_task_mode,
    show_tasks,
)


class OpenCodeEngine(BaseEngine):
    """OpenCode 引擎的具体实现"""

    OPENCODE_COMMAND = "opencode"

    def __init__(self):
        super().__init__("OpenCode", "opencode-default")

    def _get_plugin_link_dir(self):
        return (Path.cwd() / ".opencode" / "plugins").absolute()

    def ensure_plugins_link(self):
        """为 OpenCode 优化插件挂载逻辑：支持扁平化链接并自动生成通用适配器"""
        plugins_to_mount = self.get_plugins_to_mount()
        if not plugins_to_mount:
            return

        link_dir = self._get_plugin_link_dir()
        link_dir.mkdir(parents=True, exist_ok=True)

        mounted_count = 0
        for plugin_meta in plugins_to_mount:
            plugin_name = plugin_meta["name"]
            plugin_src_str = plugin_meta.get("_plugin_dir")
            if not plugin_src_str:
                continue

            plugin_src = Path(plugin_src_str).resolve()

            # 1. 优先检查是否有原生适配器
            opencode_inner_plugins = plugin_src / ".opencode" / "plugins"
            if opencode_inner_plugins.is_dir():
                # 链接内部所有的内容（根据 Review 建议：链接所有文件和文件夹而不仅仅是 JS）
                for item in opencode_inner_plugins.iterdir():
                    target_link = link_dir / item.name
                    self._safe_remove_link(target_link)
                    self._create_skill_link(item, target_link)
                    mounted_count += 1
                continue

            # 2. 如果没有原生适配器，自动生成一个通用适配器
            adapter_content = self._generate_universal_adapter(plugin_name, plugin_src)
            adapter_file = link_dir / f"ca_adapter_{plugin_name.replace('/', '_')}.js"

            # 写入生成的适配器代码 (带有 _ca_injected 标记以便清理)
            with open(adapter_file, "w", encoding="utf-8") as f:
                f.write(adapter_content)
            mounted_count += 1

        if mounted_count:
            print(
                f"🔌 Ensured {mounted_count} plugins (with auto-adapters) in {link_dir}"
            )

    def _generate_universal_adapter(self, name: str, src_path: Path) -> str:
        """生成符合 OpenCode 规范的通用 JS 适配器代码"""
        skill_md_path = src_path / "SKILL.md"
        scripts_dir = src_path / "scripts"

        # 路径处理 (Windows 兼容)
        abs_skill = str(skill_md_path.absolute()).replace("\\", "/")

        # 探测脚本
        tool_defs = []
        if scripts_dir.is_dir():
            for script in scripts_dir.iterdir():
                if script.is_file() and script.suffix in (".py", ".sh", ".ps1"):
                    safe_script_name = f"{name}_{script.stem}".replace(
                        "/", "_"
                    ).replace("-", "_")
                    tool_defs.append(
                        {
                            "name": safe_script_name,
                            "path": str(script.absolute()).replace("\\", "/"),
                            "ext": script.suffix,
                        }
                    )

        # 使用 json.dumps 安全转义所有嵌入 JS 的字符串，防止路径/名称注入
        name_js = json.dumps(name)
        skill_path_js = json.dumps(abs_skill)

        # 构建工具定义块
        tool_lines: list[str] = []
        for tool in tool_defs:
            cmd = "python" if tool["ext"] == ".py" else "sh"
            if tool["ext"] == ".ps1":
                cmd = "powershell"
            tool_name_js = json.dumps(tool["name"])
            tool_desc_js = json.dumps(
                f"Execute script from plugin {name}: {Path(tool['path']).name}"
            )
            tool_cmd_js = json.dumps(f"{cmd} {tool['path']} ")
            tool_lines.append(
                "      {\n"
                f"        name: {tool_name_js},\n"
                f"        description: {tool_desc_js},\n"
                "        execute: async (args) => {\n"
                "          const scriptArgs = typeof args === 'string' ? args : JSON.stringify(args);\n"
                f"          return await client.runShellCommand({tool_cmd_js} + scriptArgs);\n"
                "        }\n"
                "      },"
            )

        tools_block = "\n".join(tool_lines)

        # 生成 JS 模板 — 所有用户可控值通过 json.dumps 转义后嵌入
        js_code = f"""
/**
 * Generated by CodeAgent Universal Adapter
 * Plugin: {name}
 * _ca_injected: true
 */
import fs from 'fs';

export default async ({{ client }}) => {{
  const skillPath = {skill_path_js};
  const pluginName = {name_js};
  let bootstrap = "";

  if (fs.existsSync(skillPath)) {{
    const raw = fs.readFileSync(skillPath, 'utf8');
    const content = raw.replace(/^---[\\s\\S]*?---\\n/, '');
    bootstrap = `\\n<PLUGIN_CONTEXT name="${{pluginName}}">\\n${{content}}\\n</PLUGIN_CONTEXT>\\n`;
  }}

  return {{
    'experimental.chat.messages.transform': async (_input, output) => {{
      if (!bootstrap || !output.messages.length) return;
      const firstUser = output.messages.find(m => m.info.role === 'user');
      if (!firstUser || !firstUser.parts.length) return;
      if (firstUser.parts.some(p => p.text && p.text.includes('<PLUGIN_CONTEXT name="' + pluginName + '">'))) return;

      firstUser.parts.unshift({{ type: 'text', text: bootstrap }});
    }},

    tools: [
{tools_block}
    ]
  }};
}};
"""
        return js_code

    def cleanup_plugins_link(self):
        """清理所有创建的链接和生成的临时适配器"""
        link_dir = self._get_plugin_link_dir()
        if not link_dir.exists():
            return

        for item in link_dir.iterdir():
            # 1. 如果是符号链接，直接删除
            if self._is_windows_link(item) or item.is_symlink():
                self._safe_remove_link(item)
            # 2. 如果是 CodeAgent 生成的临时适配器文件，也删除
            elif item.is_file() and item.name.startswith("ca_adapter_"):
                try:
                    with open(item, "r", encoding="utf-8") as f:
                        if "_ca_injected: true" in f.read(500):
                            item.unlink()
                except Exception:
                    pass

        # 如果目录空了则删除
        if link_dir.exists() and not any(link_dir.iterdir()):
            try:
                link_dir.rmdir()
            except Exception:
                pass

    def build_command(self, message: str, non_interactive: bool) -> List[str]:
        if non_interactive:
            # 非交互模式使用 run
            return [self.OPENCODE_COMMAND, "run", message]

        # 交互模式：在当前目录启动 TUI 并注入初始提示词
        return [self.OPENCODE_COMMAND, ".", "--prompt", message]


def main():
    engine = OpenCodeEngine()
    parser = argparse.ArgumentParser(description="OpenCode Agent Controller")
    parser.add_argument("-t", "--task", nargs="?", const="", help="任务模式")
    parser.add_argument("--list", action="store_true", help="列出所有任务")
    parser.add_argument(
        "-ni", "--non-interactive", action="store_true", help="非交互模式"
    )
    parser.add_argument(
        "-y",
        "--yolo",
        action="store_true",
        default=True,
        help="开启 YOLO 模式 (默认开启)",
    )
    args, unknown = parser.parse_known_args()

    if args.list:
        show_tasks(label="Task List", file_suffix=TASK_FILE_SUFFIX)
        return

    if not require_engine_cli("opencode"):
        sys.exit(1)

    # 使用基类统一合成提示词
    full_prompt = engine.assemble_prompt(task=" ".join(unknown))

    if args.task is not None:
        task_prompt = handle_task_mode(
            args.task, label="Task", file_suffix=TASK_FILE_SUFFIX
        )
        if task_prompt:
            full_prompt = f"{full_prompt}\n\n{task_prompt}"

    # 使用临时文件引导模式，解决命令行超长问题
    concise_msg = engine.write_temp_prompt(full_prompt)

    # 统一技能链接 (挂载到 .opencode/skills)
    engine.ensure_skills_link(".opencode/skills")
    # 统一插件链接
    engine.ensure_plugins_link()

    # 注入动态钩子
    resolved_hooks = engine.get_hooks_to_inject()
    engine.inject_hooks_to_settings(".opencode/settings.json", resolved_hooks)

    env = engine.env_manager.get_env()

    try:
        final_command = engine.build_command(concise_msg, args.non_interactive)
        print(f"🚀 Launching {engine.name}...")

        engine.run_shell(final_command, env)
    finally:
        # 1. 还原配置到注入前状态
        engine.restore_settings(".opencode/settings.json")
        # 2. 清理技能链接
        engine.cleanup_skills_link(".opencode/skills")
        # 3. 清理插件链接
        engine.cleanup_plugins_link()
        # 4. 使用基类统一清理临时提示词
        engine.cleanup_temp_prompt()


if __name__ == "__main__":
    main()
