"""``core.cli`` package — re-exported via ``ca_launcher`` for backward compat."""

from .helpers import (
    FALLBACK_ENGINE,
    _ensure_project_on_path,
    _installed_root,
    _is_path_registered,
    _looks_like_project_root,
    _project_root,
    build_proxy_env,
    find_available_port,
    is_tcp_port_open,
    load_config,
)
from .main import EPILOG, CodeAgentGroup, cli, main
from .ui import (
    UI_API_PORT,
    UI_DEV_SERVER_HOST,
    UI_DEV_SERVER_PORT,
    UI_DEV_SERVER_START_TIMEOUT,
    _frontend_dist_exists,
    _frontend_root,
    _frontend_source_exists,
    _is_ui_dev_server_running,
    _open_browser,
    _start_ui_dev_server,
    _stop_ui_dev_server,
    _ui_dev_server_command,
    _wait_for_api_then_open_browser,
    run_ui_command,
)

__all__ = [
    "FALLBACK_ENGINE",
    "CodeAgentGroup",
    "EPILOG",
    "UI_API_PORT",
    "UI_DEV_SERVER_HOST",
    "UI_DEV_SERVER_PORT",
    "UI_DEV_SERVER_START_TIMEOUT",
    "_ensure_project_on_path",
    "_frontend_dist_exists",
    "_frontend_root",
    "_frontend_source_exists",
    "_installed_root",
    "_is_path_registered",
    "_is_ui_dev_server_running",
    "_looks_like_project_root",
    "_open_browser",
    "_project_root",
    "_start_ui_dev_server",
    "_stop_ui_dev_server",
    "_ui_dev_server_command",
    "_wait_for_api_then_open_browser",
    "build_proxy_env",
    "cli",
    "find_available_port",
    "is_tcp_port_open",
    "load_config",
    "main",
    "run_ui_command",
]
